### ISSUE TITLE
Any kind of trans, translate, i18n, __ filters or functions?

### ISSUE THREAD

**Issue by megant** [soywiz/atpl.js#73]
Is there or do you plan any kind of trans, translate, i18n, __ filters or functions?

**Comment by soywiz** [comment]
Ok. I could add it. Any suggestion for providing translations?

**Comment by megant** [comment]
I meant the implementation of this:

http://twig.sensiolabs.org/doc/extensions/i18n.html

currently I added a filter method to DefaultFilters, like:

    DefaultFilters.trans = function(phrase) {
        return sails.__(phrase);
    }

and it works with sailsjs well, but I think a general and framework independent solution would be much better.

**Comment by megant** [comment]
I was wrong. The solution above does not work properly. When trans filter returns with sails.__() it says:

"i18n:warn WARN: No locale found - check the context of the call to __()..."

The locale string is stored in a session variable, but I'm unable to access any session variables inside the trans filter function. How would you do it?

**Comment by soywiz** [comment]
@megant  I'm working on it right now. Probably you will have to plug somehow sails. I don't want to have dependencies here.
Maybe it would be possible to create a project extension for atpl which includes sails. Something like atpl-sails or atpl-extensions or atpl-i18n project.

**Comment by soywiz** [comment]
Ok. I have done it already.
You have trans filter, and trans block (supporting plural, notes) and standalone. It is supposed to work as twig does. Please, reopen if found any bug.

You must override `LanguageContext.trans` function which receives:

```
trans(selected:string, normal:string, plural:string, locale:string, count:number) {
    return "TRANS[" + locale + "]:" + selected;
}
```

"selected" is the textid selected from normal and plural using count. In the case you have to do manual textid selection you have all those arguments to do so.

Locale will be resolved:

If there is a variable called "locale" it will be used. In other case RuntimeContext.locale will be used which is null by default, but you can override it.

**Comment by megant** [comment]
OK. My only problem is in sailsjs, I store locale in session, like this:

// api/policies/localize.js
module.exports = function(req, res, next) {
  req.setLocale(req.session.locale);
  next();
};

(http://sailsjs.org/documentation/concepts/internationalization/locales)

But it does not affect locale in LanguageContext.trans. How could I access req.session.locale and pass it as "locale"?

**Comment by soywiz** [comment]
Im going to investigate this. In the mean time you can just pass it everytime in your templates as a plain variable locale. It should work.

**Comment by megant** [comment]
Any step forward? Just because "passing it everytime in your templates as a plain variable locale" is not a solution, sorry. :)
